### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by grumblerbear** [whoward69/DLL-VMC#1]
I clone v68 and get error when compile with CustomMods, I fix it, but next error...

CvCityCitizens.obj : error LNK2001: unresolved external symbol "enum GreatPersonTypes __cdecl GetGreatPersonFromSpecialist(enum SpecialistTypes)" (?GetGreatPersonFromSpecialist@@YA?AW4GreatPersonTypes@@W4SpecialistTypes@@@Z)

**Comment by whoward69** [comment]
You will need VS-2008 installed to be able to compile (see http://forums.civfanatics.com/showthread.php?t=479374).  If also using VS-2015 see http://forums.civfanatics.com/showthread.php?t=551613

**Comment by grumblerbear** [comment]
But I complete all 11 steps before get this error. Load VS2008 with link in this post, and all other.

**Comment by grumblerbear** [comment]
what VS version you are using? may be in the project for her all goes well...

**Comment by whoward69** [comment]
See post #1300 here http://forums.civfanatics.com/showthread.php?t=479600&page=65
